### PR TITLE
Correct spelling in howto/Pack.txt

### PR DESCRIPTION
**Pull request by fnogatz**

### CODE REVIEW

**Comment by fnogatz** [comment]
Apparently http://www.swi-prolog.org/howto/Pack.html is not yet updated. Do we need any further steps to apply the changes of this PR?

**Comment by wouterbeek** [comment]
@fnogatz The submodule update was not yet committed into plweb.  It's now added in [this commit](https://github.com/SWI-Prolog/plweb/commit/eacc7b2014a543a706dea6e646b2103ca09f2d3e).

**Comment by JanWielemaker** [comment]
In the end it has to be checked out to the servers.  I typically do that with a new release.  Sometimes I forget.   Will get there.

**Comment by fnogatz** [comment]
No problem. I was just curious about the normal process to publish the changes :)

**Pull request merged**
