### PR TITLE
Update JPL web page - link to jpl7.org

### PR DESCRIPTION
**Pull request by ssardina**
Just put a link to the official JPL doc as this is 12 years old and out-of-date

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.  Merged after removing myself as JPL designer and fixing a typo in the index.html.

**Comment by ssardina** [comment]
@JanWielemaker it seems it was not merged. Am I missing something?

**Comment by JanWielemaker** [comment]
See message with the issue.    It is merged.

**Comment by ssardina** [comment]
mm yes you are right, the files are updated in `master` here. 

I guess the pages are not rendered live from this repo but go live with a version release?

**Comment by JanWielemaker** [comment]
> I guess the pages are not rendered live from this repo but go live with a version release?

Yip.   The next version is rarely far away though :smile: .   I'm thinking about today or tomorrow.

**Comment by ssardina** [comment]
wow, already... 8.2.0 came very recently I think... Excellent.

**Comment by JanWielemaker** [comment]
> wow, already... 8.2.0 came very recently I think... Excellent.

Well, first 8.3.2, but that updates the website.  8.2.1 shouldn't be too far away either though.   Updating JPL is a bit tricky here as in the stable version we are not allowed to make changes that can break anything.   Is this the case here?

**Comment by ssardina** [comment]
I see, 8.3.2 will update website, get it.

SWIPL 8.2.0 came with the JPL that has `Rationals`, but not `Dict`. 

Dictionaries it the only "major" change/addition, but nothing should break. The rest were all documentation clean-up and the Maven upgrade for development.

We are now at 8.3.1, what would 8.2.1 be if not 8.3.1?

**Comment by JanWielemaker** [comment]
> what would 8.2.1 be if not 8.3.1

8.2.1 backports the the 8.3.1 patches that fix bugs and are highly unlikely to break anything.   Well, for the .1 version we are typically a bit more relaxed, so there will be a couple more changes that are not completely according to these rules.

**Pull request closed without merging**
